# You need to have credentials to be able to use Reddit api. For instructions 
# on setting Reddit to authenticate on non-reddit websites and applications, 
# check Reddit OAuth2 (https://github.com/reddit-archive/reddit/wiki/oauth2).
[creds]
APP_CLIENT_ID = ""
APP_CLIENT_SECRET = ""
REDDIT_USERNAME = ""
REDDIT_PW = ""
APP_NAME = ""
